{% set name = "blake3" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a76c54e91ca3a28be760575726f8dc01572734023fe88bf8dfa76913fa48a943

build:
  skip: true # [py<310]
  number: 0
  script: 
    - {{ PYTHON }} -m pip install . -vv  --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - maturin >=1.0,<2
    - pip
    - python
    - toml
  run:
    - python

test:
  imports:
    - blake3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oconnor663/blake3-py
  summary: Python bindings for the Rust blake3 crate
  description: |
    Python bindings for the official Rust implementation of BLAKE3, based on 
    PyO3. These bindings expose all the features of BLAKE3, including 
    extendable output, keying, and multithreading. The basic API matches 
    that of Python's standard hashlib module.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  dev_url: https://github.com/oconnor663/blake3-py
  doc_url: https://github.com/oconnor663/blake3-py

extra:
  recipe-maintainers:
    - maartenbreddels
    - oconnor663
